TRUNCATE TABLE `kb3_item_types`;
INSERT IGNORE INTO `kb3_item_types` VALUES ('0','#System','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('1','Character','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('2','Corporation','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('3','Region','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('4','Constellation','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('5','Solar System','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('6','Sun','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('7','Planet','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('8','Moon','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('9','Asteroid Belt','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('10','Stargate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('11','Asteroid OLD','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('12','Cargo Container','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('13','Ring','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('14','Biomass','4');
INSERT IGNORE INTO `kb3_item_types` VALUES ('15','Station','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('16','Station Services','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('17','Money','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('18','Mineral','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('19','Faction','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('20','Drug','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('23','Clone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('24','Voucher','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('25','Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('26','Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('27','Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('28','Industrial','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('29','Capsule','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('30','Titan','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('31','Shuttle','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('32','Alliance','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('38','Shield Extender','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('39','Shield Recharger','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('40','Shield Booster','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('41','Shield Transporter','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('43','Capacitor Recharger','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('46','Afterburner','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('47','Cargo Scanner','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('48','Ship Scanner','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('49','Survey Scanner','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('52','Jump Scrambler','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('53','Energy Weapon','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('54','Mining Laser','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('55','Projectile Weapon','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('56','Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('57','Power Manager','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('59','Gyrostabilizer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('60','Damage Control','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('61','Capacitor Battery','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('62','Armor Repair Unit','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('63','Hull Repair Unit','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('65','Stasis Web','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('67','Energy Transfer Array','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('68','Energy Vampire','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('71','Energy Destabilizer','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('72','Smart Bomb','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('74','Hybrid Weapon','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('76','Capacitor Booster','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('77','Shield Hardener','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('78','Hull Mods','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('80','ECM Burst','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('82','Passive Targeting System','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('83','Ammo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('84','Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('85','Hybrid Ammo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('86','Frequency Crystal','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('87','Capacitor Booster Charge','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('88','Defender Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('89','Torpedo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('90','Bomb','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('91','FOF Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('92','Mine','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('94','Trading','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('95','Trade Session','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('96','Automated Targeting System','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('97','Proximity Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('98','Armor Coating','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('99','Sentry Gun','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('100','Combat Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('101','Mining Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('104','Clone Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('105','Frigate Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('106','Cruiser Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('107','Battleship Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('108','Industrial Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('109','Capsule Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('110','Titan Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('111','Shuttle Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('118','Shield Extender Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('119','Shield Recharger Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('120','Shield Booster Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('121','Shield Transporter Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('123','Capacitor Recharger Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('126','Afterburner Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('127','Cargo Scanner Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('128','Ship Scanner Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('129','Survey Scanner Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('130','ECM Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('131','ECCM Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('132','Jump Scrambler Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('133','Energy Weapon Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('134','Mining Laser Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('135','Projectile Weapon Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('136','Missile Launcher Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('137','Power Manager Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('139','Fast Loader Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('140','Damage Control Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('141','Capacitor Battery Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('142','Armor Repair Unit Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('143','Hull Repair Unit Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('145','Stasis Web Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('147','Energy Transfer Array Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('148','Energy Vampire Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('151','Energy Destabilizer Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('152','Smart Bomb Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('154','Hybrid Weapon Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('156','Capacitor Booster Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('157','Shield Hardener Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('158','Hull Mods Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('160','ECM Burst Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('161','Passive Targeting System Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('162','Automated Targeting System Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('163','Armor Coating Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('165','Ammo Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('166','Missile Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('167','Hybrid Ammo Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('168','Frequency Crystal Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('169','Capacitor Booster Charge Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('170','Defender Missile Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('171','Torpedo Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('172','Bomb Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('173','FOF Missile Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('174','Mine Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('175','Proximity Drone Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('176','Combat Drone Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('177','Mining Drone Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('178','Drug Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('180','Protective Sentry Gun','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('182','Police Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('185','Pirate Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('186','Wreck','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('190','Bloodline Bonus','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('191','Physical Benefit','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('192','Physical Handicap','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('193','Phobia Handicap','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('194','Social Handicap','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('195','Amarr Education','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('196','Caldari Education','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('197','Gallente Education','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('198','Minmatar Education','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('199','Career Bonus','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('201','ECM','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('202','ECCM','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('203','Sensor Backup Array','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('205','Heat Sink','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('208','Remote Sensor Damper','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('209','Tracking Link','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('210','Signal Amplifier','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('211','Tracking Enhancer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('212','EB2 - Sensor Booster','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('213','EB3 - Tracking Computer','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('218','Heat Sink Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('223','EB2 - Sensor Booster Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('224','EB3 - Tracking Computer Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('225','Cheat Module Group','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('226','Large Collidable Object','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('227','Cloud','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('237','Rookie ship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('255','Gunnery','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('256','Missile Launcher Operation','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('257','Spaceship Command','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('258','Leadership','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('266','Corporation Management','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('267','Learning','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('268','Industry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('269','Mechanic','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('270','Science','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('271','Engineering','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('272','Electronics','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('273','Drones','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('274','Trade','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('275','Navigation','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('278','Social','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('279','LCO Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('280','General','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('281','Frozen','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('282','Radioactive','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('283','Livestock','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('284','Biohazard','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('285','CPU Enhancer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('286','Tutorial Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('287','Rogue Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('288','Faction Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('289','Projected ECCM','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('290','Remote Sensor Booster','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('291','Tracking Disrupter','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('295','Shield Amplifier','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('296','Shield Amplifier Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('297','Convoy','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('298','Convoy Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('299','Repair Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('300','Cyberimplant','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('301','Concord Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('302','Magnetic Field Stabilizer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('303','Booster','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('304','DNA Mutator','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('305','Comet','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('306','Spawn Container','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('307','Construction Platform','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('308','Countermeasure Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('309','Autopilot','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('310','Beacon','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('311','Refining Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('312','Planetary Cloud','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('313','Drugs','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('314','Miscellaneous','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('315','Anti Warp Scrambler','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('316','Gang Coordinator','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('317','Computer Interface Node','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('318','Landmark','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('319','Large Collidable Structure','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('320','Dynamic Shield Calibrator','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('321','Shield Disruptor','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('323','Billboard','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('324','Elite Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('325','Armor Repair Projector','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('326','Armor Plating Energized','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('328','Armor Hardener','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('329','Armor Reinforcer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('330','Cloaking Device','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('331','Deep Core Mining Laser','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('332','Tool','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('333','Research Material','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('334','Construction Components','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('335','Temporary Cloud','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('336','Mobile Sentry Gun','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('337','Mission Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('338','Shield Boost Amplifier','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('339','Auxiliary Power Core','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('340','Secure Cargo Container','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('341','Signature Scrambling','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('342','Anti Warp Scrambler Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('343','Tracking Disruptor Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('344','Tracking Enhancer Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('345','Tracking Link Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('346','Co-Processor Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('347','Signal Amplifier Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('348','Armor Hardener Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('349','Armor Reinforcer Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('350','Armor Repair Projector Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('352','Auxiliary Power Core Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('353','GM Modules','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('355','Refinables','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('356','Tool Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('357','DroneBayExpander','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('358','Elite Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('360','Shield Boost Amplifier Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('361','Mobile Warp Disruptor','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('363','Ship Maintenance Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('364','Mobile Storage','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('365','Control Tower','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('366','Warp Gate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('367','Ballistic Control system','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('368','Global Warp Disruptor','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('369','Ship Logs','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('370','Criminal Tags','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('371','Mobile Warp Disruptor Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('372','Advanced Autocannon Ammo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('373','Advanced Railgun Ammo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('374','Advanced Beam Laser Crystal','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('375','Advanced Pulse Laser Crystal','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('376','Advanced Artillery Ammo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('377','Advanced Blaster Ammo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('378','Cruise Control','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('379','Target Painter','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('380','Elite Industrial','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('381','Elite Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('382','Shipping Crates','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('383','Destructible Sentry Gun','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('384','Light Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('385','Heavy Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('386','Cruise Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('387','Rocket','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('394','FoF Light Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('395','FoF Heavy Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('396','FoF Cruise Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('397','Assembly Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('400','Ballistic Control System Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('401','Cloaking Device Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('404','Silo','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('405','Anti Cloaking Pulse','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('406','Smartbomb Supercharger','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('407','Drone Control Unit','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('408','Drone Control Unit Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('409','Empire Insignia Drops','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('410','Anti Cloaking Pulse Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('411','Force Field','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('413','Mobile Laboratory','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('414','Mobile Power Core','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('416','Moon Mining','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('417','Mobile Missile Sentry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('418','Mobile Shield Generator','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('419','Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('420','Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('422','Gas Isotopes','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('423','Ice Product','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('425','Orbital Assault Unit','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('426','Mobile Projectile Sentry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('427','Moon Materials','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('428','Intermediate Materials','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('429','Composite','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('430','Mobile Laser Sentry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('432','Deadspace Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('433','Deadspace Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('434','Deadspace Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('435','Deadspace Overseer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('436','Simple Reaction','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('438','Mobile Reactor','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('439','Electronic Warfare Battery','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('440','Sensor Dampening Battery','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('441','Stasis Webification Battery','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('443','Warp Scrambling Battery','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('444','Shield Hardening Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('445','Force Field Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('446','Customs Official','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('447','Construction Component Blueprints','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('448','Audit Log Secure Container','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('449','Mobile Hybrid Sentry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('450','Arkonor','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('451','Bistot','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('452','Crokite','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('453','Dark Ochre','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('454','Hedbergite','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('455','Hemorphite','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('456','Jaspet','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('457','Kernite','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('458','Plagioclase','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('459','Pyroxeres','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('460','Scordite','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('461','Spodumain','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('462','Veldspar','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('463','Mining Barge','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('464','Strip Miner','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('465','Ice','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('467','Gneiss','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('468','Mercoxit','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('469','Omber','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('470','Unanchoring Drone','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('471','Corporate Hangar Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('472','System Scanner','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('473','Tracking Array','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('474','Acceleration Gate Keys','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('475','Microwarpdrive','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('476','Citadel Torpedo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('477','Mining Barge Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('478','System Scanner Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('479','Scanner Probe','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('480','Stealth Emitter Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('481','Scan Probe Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('482','Mining Crystal','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('483','Frequency Mining Laser','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('484','Complex Reactions','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('485','Dreadnought','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('486','Scan Probe Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('487','Destroyer Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('489','Battlecruiser Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('490','Strip Miner Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('492','Survey Probe','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('493','Overseer Personal Effects','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('494','Deadspace Overseer\'s Structure','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('495','Deadspace Overseer\'s Sentry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('496','Deadspace Overseer\'s Belongings','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('497','Fuel','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('498','Officer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('499','New EW Testing','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('500','Snowballs','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('501','Snowball Launcher','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('502','Cosmic Signature','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('503','Elite Industrial Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('504','Target Painter Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('505','Fake Skills','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('506','Cruise Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('507','Rocket Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('508','Siege Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('509','Standard Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('510','Heavy Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('511','Assault Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('512','Defender Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('513','Freighter','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('514','ECM Stabilizer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('515','Siege Module','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('516','Siege Module Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('517','Agents in Space','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('518','Anti Ballistic Defense System','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('519','Terran Artifacts','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('520','Storyline Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('521','Identification','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('522','Storyline Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('523','Storyline Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('524','Citadel Missile Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('525','Freighter Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('526','Commodities','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('527','Storyline Mission Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('528','Artifacts and Prototypes','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('529','Information and Lore','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('530','Materials and Compounds','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('531','Jump Drive Fuel','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('532','Gang Coordinator Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('533','Storyline Mission Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('534','Storyline Mission Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('535','Construction Platform Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('536','Station Components','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('537','Dreadnought Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('538','Data Miners','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('539','Destructible Agents In Space','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('540','Elite Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('541','Elite Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('543','Elite Mining Barge','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('544','Cap Drain Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('545','Warp Scrambling Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('546','Mining Upgrade','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('547','Carrier','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('548','Warp Disruption Probe','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('549','Fighter Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('550','Asteroid Angel Cartel Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('551','Asteroid Angel Cartel Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('552','Asteroid Angel Cartel Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('553','Asteroid Angel Cartel Officer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('554','Asteroid Angel Cartel Hauler','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('555','Asteroid Blood Raiders Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('556','Asteroid Blood Raiders Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('557','Asteroid Blood Raiders Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('558','Asteroid Blood Raiders Hauler','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('559','Asteroid Blood Raiders Officer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('560','Asteroid Guristas Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('561','Asteroid Guristas Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('562','Asteroid Guristas Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('563','Asteroid Guristas Hauler','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('564','Asteroid Guristas Officer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('570','Asteroid Serpentis Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('571','Asteroid Serpentis Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('572','Asteroid Serpentis Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('573','Asteroid Serpentis Hauler','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('574','Asteroid Serpentis Officer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('575','Asteroid Angel Cartel Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('576','Asteroid Angel Cartel BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('577','Asteroid Blood Raiders Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('578','Asteroid Blood Raiders BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('579','Asteroid Guristas Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('580','Asteroid Guristas BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('583','Asteroid Serpentis Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('584','Asteroid Serpentis BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('585','Remote Hull Repairer','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('586','Drone Modules','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('588','Super Weapon','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('589','Bubble Probe Launcher','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('590','Jump Portal Generator','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('593','Deadspace Angel Cartel BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('594','Deadspace Angel Cartel Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('595','Deadspace Angel Cartel Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('596','Deadspace Angel Cartel Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('597','Deadspace Angel Cartel Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('602','Deadspace Blood Raiders BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('603','Deadspace Blood Raiders Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('604','Deadspace Blood Raiders Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('605','Deadspace Blood Raiders Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('606','Deadspace Blood Raiders Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('611','Deadspace Guristas BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('612','Deadspace Guristas Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('613','Deadspace Guristas Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('614','Deadspace Guristas Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('615','Deadspace Guristas Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('620','Deadspace SanshaÃ¢â‚¬â„¢s Nation BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('621','Deadspace SanshaÃ¢â‚¬â„¢s Nation Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('622','Deadspace SanshaÃ¢â‚¬â„¢s Nation Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('623','Deadspace SanshaÃ¢â‚¬â„¢s Nation Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('624','Deadspace SanshaÃ¢â‚¬â„¢s Nation Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('629','Deadspace Serpentis BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('630','Deadspace Serpentis Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('631','Deadspace Serpentis Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('632','Deadspace Serpentis Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('633','Deadspace Serpentis Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('638','Navigation Computer','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('639','Electronic Warfare Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('640','Logistic Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('641','Stasis Webifying Drone','6');
INSERT IGNORE INTO `kb3_item_types` VALUES ('642','Super Gang Enhancer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('643','Carrier Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('644','Drone Navigation Computer','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('645','Drone Damage Modules','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('646','Drone Tracking Modules','2');
INSERT IGNORE INTO `kb3_item_types` VALUES ('647','Drone Control Range Module','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('648','Advanced Rocket','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('649','Freight Container','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('650','Tractor Beam','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('651','Super Weapon Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('652','Lease','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('653','Advanced Light Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('654','Advanced Assault Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('655','Advanced Heavy Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('656','Advanced Cruise Missile','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('657','Advanced Torpedo','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('658','Cynosural Field','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('659','Mothership','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('660','Vampire Slayer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('565','Asteroid Sansha\'s Nation Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('566','Asteroid Sansha\'s Nation Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('567','Asteroid Sansha\'s Nation Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('568','Asteroid Sansha\'s Nation Hauler','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('569','Asteroid Sansha\'s Nation Officer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('581','Asteroid Sansha\'s Nation Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('582','Asteroid Sansha\'s Nation BattleCruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('661','Simple Biochemical Reactions','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('662','Complex Biochemical Reactions','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('663','Mercoxit Mining Crystal','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('665','Mission Amarr Empire Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('666','Mission Amarr Empire Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('667','Mission Amarr Empire Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('668','Mission Amarr Empire Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('669','Mission Amarr Empire Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('670','Mission Amarr Empire Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('671','Mission Caldari State Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('672','Mission Caldari State Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('673','Mission Caldari State Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('674','Mission Caldari State Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('675','Mission Caldari State Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('676','Mission Caldari State Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('677','Mission Gallente Federation Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('678','Mission Gallente Federation Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('679','Mission Gallente Federation Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('680','Mission Gallente Federation Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('681','Mission Gallente Federation Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('682','Mission Gallente Federation Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('683','Mission Minmatar Republic Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('684','Mission Minmatar Republic Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('685','Mission Minmatar Republic Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('686','Mission Minmatar Republic Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('687','Mission Khanid Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('688','Mission Khanid Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('689','Mission Khanid Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('690','Mission Khanid Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('691','Mission Khanid Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('692','Mission Khanid Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('693','Mission CONCORD Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('694','Mission CONCORD Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('695','Mission CONCORD Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('696','Mission CONCORD Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('697','Mission CONCORD Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('698','Mission CONCORD Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('699','Mission Mordu Frigate','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('700','Mission Mordu Destroyer','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('701','Mission Mordu Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('702','Mission Mordu Battlecruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('703','Mission Mordu Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('704','Mission Mordu Other','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('705','Mission Minmatar Republic Cruiser','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('706','Mission Minmatar Republic Battleship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('707','Jump Portal Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('709','Scanner Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('710','Logistics Array','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('711','Harvestable Cloud','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('712','Biochemical Material','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('714','Processed Gas Clouds','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('715','Destructible Agents In Space','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('716','Data Interfaces','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('718','Booster Blueprints','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('719','Destructible Agents With Guns','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('720','Destructible Agent NPCs','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('721','Temp','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('737','Gas Cloud Harvester','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('762','Inertia Stabilizer','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('763','Nanofiber Internal Structure','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('764','Overdrive Injector System','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('765','Expanded Cargohold','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('766','Power Diagnostic System','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('767','Capacitor Power Relay','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('768','Capacitor Flux Coil','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('769','Reactor Control Unit','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('770','Shield Flux Coil','3');
INSERT IGNORE INTO `kb3_item_types` VALUES ('771','Missile Launcher Heavy Assault','1');
INSERT IGNORE INTO `kb3_item_types` VALUES ('773','Rig Armor','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('774','Rig Shield','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('775','Rig Energy Weapon','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('776','Rig Hybrid Weapon','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('777','Rig Projectile Weapon','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('778','Rig Drones','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('779','Rig Launcher','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('780','Rig Electronics','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('781','Rig Energy Grid','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('782','Rig Astronautic','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('786','Rig Electronics Superiority','5');
INSERT IGNORE INTO `kb3_item_types` VALUES ('738','Cyber Armor','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('740','Cyber Electronics','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('741','Cyber Engineering','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('742','Cyber Gunnery','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('743','Cyber Industry','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('744','Cyber Leadership','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('745','Cyber Learning','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('746','Cyber Missile','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('747','Cyber Navigation','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('748','Cyber Science','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('749','Cyber Shields','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('772','Assault Missile','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('783','Cyber X Specials','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('785','Script','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('722','Advanced Hybrid Ammo Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('723','Tractor Beam Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('724','Implant Blueprints','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('725','Advanced Projectile Ammo Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('726','Advanced Frequency Crystal Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('727','Mining Crystal Blueprint','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('728','Decryptors - Amarr','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('729','Decryptors - Minmatar','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('730','Decryptors - Gallente','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('731','Decryptors - Caldari','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('732','Decryptors - Sleepers','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('733','Decryptors - Yan Jung','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('734','Decryptors - Takmahl','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('735','Decryptors - Talocan','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('754','Salvaged Materials','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('784','Large Collidable Ship','0');
INSERT IGNORE INTO `kb3_item_types` VALUES ('787','Rig Blueprint','0');
